mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant_menu.urls'))
]

restaurant_menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MenuList.as_view(), name='home'),
    # path('menuItems/', views.)
]

restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User

CATEGORIES = (
    ("starters", "Starters"),
    ("salads", "Salads"),
    ("main_dishes", "Main Dishes"),
    ("desserts", "Desserts")
)

STATUS = (
    (0, "Unavailable"),
    (1, "Available")
)

class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    description = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=200, choices=CATEGORIES)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUS, default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updates = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.meal

restaurant_menu/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, CATEGORIES


class MenuList(generic.ListView):
    queryset = Item.objects.order_by("date_created")
    template_name = "index.html"


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meals"] = CATEGORIES
        return context


class MenuItemDetail(generic.DetailView):
    model = Item
    template_name = "menu_item.html"

restaurant_menu/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WearIt</title>
</head>
<body>
    <h1>Restaurant Menu</h1>
    {% for meal in meals %}
        <h2>{{ meal.1 }}</h2>
        {% for row in item_list %}
            {% if row.category == meal.0 %}
                {% if row.status == 0 %}
                    <h3><del>{{ row.meal }}</del></h3>
                    <p>{{ row.description }}</p>
                    <p>{{ row.price }}</p>
                {% else %}
                    <h3>{{ row.meal }}</h3>
                    <p>{{ row.description }}</p>
                    <p>{{ row.price }}</p>
                {% endif %}
            {% endif %}
        {% endfor %}
    {% endfor %}
</body>
</html>

restaurant_menu/templates/menu_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Menu Items</h1>
</body>
</html>